# Generated by Django 3.1.7 on 2021-06-24 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='post_dat',
            new_name='post_date',
        ),
    ]
