# Generated by Django 3.1.7 on 2021-06-19 16:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Vote', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='down_vote_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='down_vote_user', to=settings.AUTH_USER_MODEL, unique=True),
        ),
        migrations.AlterField(
            model_name='vote',
            name='up_vote_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='up_vote_user', to=settings.AUTH_USER_MODEL, unique=True),
        ),
    ]
