# Generated by Django 3.1.7 on 2021-05-27 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('faculty_id', models.AutoField(default=None, primary_key=True, serialize=False)),
                ('faculty_name', models.CharField(default=None, max_length=200)),
            ],
        ),
    ]
