# Generated by Django 3.1.7 on 2021-05-28 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Faculty', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='faculty_name',
            field=models.CharField(default=None, max_length=200, unique=True),
        ),
    ]
