# Generated by Django 3.1.7 on 2021-05-27 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Faculty', '0001_initial'),
        ('Program', '0001_initial'),
        ('Student', '0001_initial'),
        ('College', '0002_auto_20210527_1433'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enroll',
            fields=[
                ('enroll_id', models.AutoField(default=None, primary_key=True, serialize=False)),
                ('college', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='College.college')),
                ('faculty', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Faculty.faculty')),
                ('program', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Program.program')),
                ('student', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Student.student')),
            ],
        ),
    ]
