# Generated by Django 3.1.7 on 2021-05-28 06:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0001_initial'),
        ('College', '0003_auto_20210527_1551'),
        ('Program', '0002_auto_20210528_1213'),
        ('Faculty', '0002_auto_20210528_1213'),
        ('Enroll', '0003_auto_20210528_1215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enroll',
            name='college',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='college', to='College.college'),
        ),
        migrations.AlterField(
            model_name='enroll',
            name='faculty',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='faculty', to='Faculty.faculty'),
        ),
        migrations.AlterField(
            model_name='enroll',
            name='program',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='program', to='Program.program'),
        ),
        migrations.AlterField(
            model_name='enroll',
            name='student',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='student', to='Student.student'),
        ),
    ]
