# Generated by Django 3.1.7 on 2021-05-27 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('College', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='college',
            name='faculty',
        ),
        migrations.RemoveField(
            model_name='college',
            name='program',
        ),
    ]
