# Generated by Django 3.1.7 on 2021-05-27 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('College', '0002_auto_20210527_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='college',
            name='college_name',
            field=models.CharField(default=None, max_length=200, unique=True),
        ),
    ]
